from pathlib import Path
import json,re,html
P=Path(__file__).resolve().parents[1]
BASE='https://hawaiimainlandmoving.com'
def esc(s):return html.escape(s,quote=True)
def outlink(url,ctx,text,kind='modelmoving'):
 return f'<a href="{url}?utm_source=hawaiimainlandmoving.com&amp;utm_medium=referral&amp;utm_campaign={ctx}" data-event="hmm_{kind}_click" target="_blank" rel="noopener">{text}</a>'
NAV='''<a class="skip" href="#main">Skip to content</a><header><div class="wrap nav"><a class="brand" href="/">Hawaii ↔ Mainland<small>Moving, made clearer.</small></a><button class="menu" id="menu" aria-controls="navigation" aria-expanded="false" aria-label="Open navigation">☰</button><nav class="navlinks" id="navigation" aria-label="Main navigation"><a href="/hawaii-to-mainland-moving/">Moving guides</a><a href="/hawaii-mainland-moving-cost/">Cost factors</a><a href="/hawaii-moving-shipping-process/">The journey</a><a href="/#quote" class="btn" data-event="hmm_quote_cta_click">Plan my move ↗</a></nav></div></header>'''
def footer(ctx):return f'''<footer><div class="wrap"><div class="footer-grid"><div><a class="brand" href="/">Hawaii ↔ Mainland<small>Operated by ModelMoving</small></a><p>HawaiiMainlandMoving.com is operated by ModelMoving, a moving quote request and matching platform that helps connect customers with selected moving partners based on route, timing, availability and move details.</p><p>Final pricing, service terms, availability and transportation arrangements are provided by the selected moving provider.</p></div><div class="footer-links"><strong>Plan your crossing</strong><a href="/hawaii-to-mainland-moving/">Hawaii to mainland</a><a href="/mainland-to-hawaii-moving/">Mainland to Hawaii</a><a href="/hawaii-mainland-moving-cost/">Moving costs</a><a href="/moving-a-car-from-hawaii-to-mainland/">Moving your vehicle</a><a href="/oahu-to-mainland-moving/">Oahu</a><a href="/maui-to-mainland-moving/">Maui</a><a href="/big-island-to-mainland-moving/">Big Island</a></div><div class="footer-links"><strong>About your request</strong><a href="/how-it-works/">How it works</a><a href="/about/">About us</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a>{outlink('https://modelmoving.com/',ctx+'_footer','ModelMoving')}{outlink('https://moveready.modelmoving.com/',ctx+'_ready','MoveReady','moveready')}</div></div><div class="copyright">© 2026 HawaiiMainlandMoving.com · Operated by ModelMoving · <a href="https://unsplash.com/photos/93B6TiJlk5Y" target="_blank" rel="noopener">Photo by Michael Olsen / Unsplash</a></div></div></footer>'''
def page(slug,title,desc,body,faqs=None):
 url=BASE+'/'+(slug+'/' if slug else '')
 graph=[{'@type':'WebSite','@id':BASE+'/#website','url':BASE+'/','name':'HawaiiMainlandMoving.com'},{'@type':'WebPage','@id':url+'#webpage','url':url,'name':title,'description':desc,'isPartOf':{'@id':BASE+'/#website'}}]
 if faqs:graph.append({'@type':'FAQPage','mainEntity':[{'@type':'Question','name':q,'acceptedAnswer':{'@type':'Answer','text':a}} for q,a in faqs]})
 doc=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{url}"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title)}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{url}"><meta property="og:site_name" content="HawaiiMainlandMoving.com"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="{esc(title)}"><meta name="twitter:description" content="{esc(desc)}"><meta name="theme-color" content="#052c37"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/site.css"><script async src="https://www.googletagmanager.com/gtag/js?id=G-KJPYXXWGEV"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','G-KJPYXXWGEV');</script><script type="application/ld+json">{json.dumps({'@context':'https://schema.org','@graph':graph})}</script><script defer src="/assets/site.js"></script></head><body>{NAV}{body}{footer(slug or 'homepage')}</body></html>'''
 path=P/slug/'index.html' if slug else P/'index.html';path.parent.mkdir(exist_ok=True);path.write_text(doc)
def faqhtml(items):return '<div class="faq">'+''.join(f'<details><summary>{q}</summary><p>{a}</p></details>' for q,a in items)+'</div>'
def cta():return '<section class="section"><div class="wrap cta"><div><div class="kicker">Your next chapter starts with a plan</div><h2>Let’s connect the details.</h2><p>Share your route, timing and what’s coming with you.</p></div><a class="btn dark" href="/#quote" data-event="hmm_quote_cta_click">Get my moving options ↗</a></div></section>'
DATA=[]
def add(slug,title,desc,sections,faqs):DATA.append((slug,title,desc,sections,faqs))
add('hawaii-to-mainland-moving','Hawaii to Mainland Moving: A Practical Planning Guide','Plan a Hawaii-to-mainland household move: inventory, island pickup, ocean transport, mainland delivery and the questions to ask before booking.',[
('A household move with more than one handoff','''<p>A Hawaii-to-mainland move needs a plan for both the ocean crossing and the homes at either end. Start with the actual pickup address, your mainland city or ZIP and the belongings you want to bring. “Two bedrooms” helps start a conversation; an inventory makes that conversation more useful.</p><p>Think about what you will need while the shipment is unavailable. Keep travel documents, medication, essential work equipment and a practical arrival kit with you. Coordinate your own travel separately from the shipment rather than assuming you will arrive together.</p>'''),
('Build an inventory before comparing options','''<p>Work room by room and separate what you will ship, sell, donate or carry yourself. Include outdoor furniture, storage lockers and oversized pieces that are easy to overlook. Photograph fragile or unusual items and record dimensions for anything that may need special handling.</p><ul><li>List furniture and estimate packed boxes by room.</li><li>Flag artwork, glass, pianos and items requiring disassembly.</li><li>Ask the provider which items cannot be accepted and how owner-packed boxes are treated.</li><li>Request a revised scope if the inventory changes materially.</li></ul>'''),
('Confirm the island collection plan','''<p>Give the provider the exact island and neighborhood, not just “Hawaii.” Explain stairs, long carries, loading access, elevators and building reservations. A narrow driveway or limited loading window should be part of the discussion before pickup.</p><p>Use the <a href="/oahu-to-mainland-moving/">Oahu</a>, <a href="/maui-to-mainland-moving/">Maui</a> or <a href="/big-island-to-mainland-moving/">Big Island</a> guide to prepare location-specific questions. For Kauai or another location, include the exact address and ask for coverage confirmation.</p>'''),
('Understand what happens after pickup','''<p>Depending on the provider, route, shipment and service plan, the move may involve consolidation, ocean transportation, mainland handling and inland delivery. Ask which stages are included, who coordinates them and whom you contact when the plan changes.</p><p>A sailing estimate does not describe the entire door-to-door move. Ask separately about collection, readiness for ocean transport, arrival handling and the destination delivery window. Our <a href="/hawaii-moving-shipping-process/">shipping-process guide</a> helps you structure that conversation.</p>'''),
('Compare the whole scope','''<p>Use the same inventory and service requests for each estimate. Check packing, origin and destination handling, storage, delivery access and any vehicle arrangements. Review payment, cancellation and claims terms directly with the provider before agreeing.</p><p>If your mainland home will not be ready, identify the storage gap early and ask how it affects delivery coordination. Review the <a href="/hawaii-mainland-moving-cost/">cost factors</a> before requesting options.</p>''')], [('Is the ocean crossing the full transit time?','No. Pickup, consolidation where applicable, arrival handling and inland delivery can add stages. Ask the provider for the complete service plan.'),('Can I request a move from Kauai?','Yes, you can submit a request with your exact location. Coverage and availability must be confirmed by a selected provider.')])
add('mainland-to-hawaii-moving','Mainland to Hawaii Moving: Plan Your Island Arrival','Prepare for a mainland-to-Hawaii move with destination-island planning, shipment decisions, building access and coordinated delivery.',[
('Choose the destination island before the service plan','''<p>A mainland-to-Hawaii move is not fully described by a Hawaii destination. Identify the island and delivery community, and say whether you already have a permanent address. If the address is uncertain, explain your likely area and ask how a later change could affect the quote.</p><p>The reverse trip deserves its own planning. You need mainland collection, ocean arrangements and an island delivery plan that matches your property and availability. Do not assume a service to one island is automatically available on another.</p>'''),
('Decide what earns its place in the shipment','''<p>Measure the furniture you want to bring against your destination floor plan, doors and access route where possible. Separate sentimental and essential items from pieces you could replace. Build an inventory before choosing a shipment scope rather than using your mainland room count alone.</p><p>If you are downsizing, remove sold or donated pieces from the final list. Tell the provider about bicycles, outdoor equipment and unusually large items so it can give preparation guidance. Ask for current restrictions before packing; do not assume plants, food, soil-bearing equipment or other regulated items are acceptable.</p>'''),
('Plan for the first days on the island','''<p>Carry the essentials you need for work, daily living and travel. Decide how you will manage if the home is ready before the goods arrive—or if the goods are ready before you can receive them. Temporary accommodation and household shipment timing are separate decisions.</p><p>For an apartment or condo, contact the property manager about loading space, elevator reservations and permitted delivery hours. Give those details to the provider while the service is being planned, especially if a reservation must change when delivery timing changes.</p>'''),
('Ask who coordinates island delivery','''<p>Have the provider explain the arrival and local-delivery stages for your specific island. Ask who contacts you, what notices to expect and what happens if you are unavailable. If storage may be needed, clarify its location, charges and the process for scheduling final delivery.</p><p>A vehicle can involve separate preparation and release arrangements. Review the <a href="/moving-a-car-from-hawaii-to-mainland/">vehicle-planning questions</a> with the provider for your actual direction; documentation and handling requirements should be confirmed directly.</p>'''),
('Request options with useful detail','''<p>Submit your mainland pickup city, destination island, approximate date and move size. Add your inventory concerns, packing needs and access limits to the notes. Your request goes to ModelMoving for matching based on route, timing, availability and move details.</p><p>Read <a href="/how-it-works/">how matching works</a> and use the <a href="/hawaii-mainland-moving-cost/">cost guide</a> to compare what each provider actually includes.</p>''')],[('Can I use the quote form for mainland to Hawaii?','Yes. Select Mainland to Hawaii in the direction field, then enter your mainland origin and Hawaii destination.'),('What if I do not have my final Hawaii address?','Give the island and expected community, explain the uncertainty in notes and ask the provider how an address change or storage gap would affect the plan.')])
add('hawaii-mainland-moving-cost','Hawaii–Mainland Moving Costs: What Shapes Your Quote','Understand Hawaii-mainland moving cost factors without fake instant prices: shipment, packing, access, island logistics, storage and delivery.',[
('A useful estimate starts with a defined shipment','''<p>Your Hawaii-mainland quote should reflect the belongings, services and route you actually need. A small apartment with easy access and a flexible schedule presents a different scope from a large household with packing, storage and a vehicle. The destination city matters alongside the island.</p><p>A clear inventory gives your provider a useful starting point for pricing. Ask each provider what measurement or pricing basis it uses and what could change after its survey or inventory review. Keep a copy of the inventory used for the estimate.</p>'''),
('Separate the cost factors','''<ul><li><strong>Shipment size:</strong> furniture, boxes and special handling affect the proposed scope.</li><li><strong>Packing:</strong> full service, fragile-only help and materials should be distinguished.</li><li><strong>Island collection:</strong> the address and local access need to match the offered service.</li><li><strong>Ocean and handling stages:</strong> ask what is included and what is separate.</li><li><strong>Mainland delivery:</strong> identify the final city and property access.</li><li><strong>Storage:</strong> discuss timing gaps and any additional handling.</li><li><strong>Vehicle:</strong> confirm whether it is a separate quotation or booking.</li></ul>'''),
('Compare like-for-like estimates','''<p>Send the same inventory, dates and service requests to each provider. A low total may describe less work rather than a better value. Look for an itemized explanation of packing, collection, transportation, destination delivery and exclusions.</p><p>Ask what circumstances can trigger additional charges: changed inventory, inaccessible loading, storage, a missed receiving window or a changed address. The provider should explain its own terms before you commit. Review and accept the selected provider’s written proposal when you are ready to book.</p>'''),
('Keep a comparison checklist','''<div class="callout"><p>For each proposal, record: inventory date; pickup and delivery locations; packing scope; included transport stages; estimated windows; storage terms; payment milestones; cancellation terms; and the contact responsible for updates.</p></div><p>Also request the provider’s written explanation of loss or damage protection, exclusions and claims handling. Coverage should never be inferred from general website language or from the fact that several stages are coordinated together.</p>'''),
('Improve the scope before cutting the budget','''<p>Decide which items you actually want in the new home. Tell the provider if your dates have flexibility and ask which service choices are available for your route. Consider the practical cost of replacing an item, not just its size in the shipment.</p><p>Use the <a href="/hawaii-to-mainland-moving/">primary planning guide</a> to prepare an inventory and the <a href="/hawaii-moving-shipping-process/">process guide</a> to check handoffs. Then <a href="/#quote" data-event="hmm_quote_cta_click">request moving options</a> with a consistent scope.</p>''')],[('Does this website provide instant moving prices?','No. The site helps you identify cost factors and request provider pricing based on the actual move.'),('Is the vehicle included in a household quote?','Do not assume so. Tell the provider you need vehicle transport and ask it to identify the separate or included scope in writing.')])
for slug,island,community,access in [('oahu','Oahu','Honolulu, Kapolei, Kailua or another Oahu community','condo elevators, loading reservations, parking limits and building move rules'),('maui','Maui','Kahului, Kihei, Wailuku or another Maui community','property access, narrow approaches, loading space and community restrictions'),('big-island','Big Island','Hilo, Kailua-Kona, Waimea or another Hawaii Island community','long driveways, gates, road access and the distance between the collection address and proposed handoff')]:
 add(slug+'-to-mainland-moving',island+' to Mainland Moving: Pickup & Delivery Planning',f'Plan a {island}-to-mainland household move with exact pickup details, inventory, access questions, packing choices and mainland delivery coordination.',[
 ('Start with your '+island+' address',f'''<p>Moving from {community}? Give the provider your actual pickup town and ZIP, the mainland destination and a realistic inventory. An island name is a useful starting point, but it does not confirm address-level coverage or a collection schedule.</p><p>For {island}, discuss {access}. Share photographs of difficult access if the provider requests them. A complete description helps it assess whether the planned equipment and collection method fit your property.</p>'''),
 ('Prepare the pickup conversation',f'''<p>Before requesting a final proposal, walk the route from your home to the loading area. Note stairs, gates, height limits and any restrictions on when loading can happen. If a property manager must approve the move, find out the process early.</p><ul><li>Provide the full {island} pickup location and property type.</li><li>List large or fragile pieces and their dimensions.</li><li>Identify parking, loading and access constraints.</li><li>Explain whether you want full packing, partial packing or collection of packed goods.</li><li>Include storage needs and any separate pickup address.</li></ul>'''),
 ('Ask how collection connects to the ocean stage',f'''<p>Ask the selected provider to describe its proposed {island} service from pickup through ocean transportation. Depending on the provider and shipment, handling or consolidation may be involved. Have it explain where responsibility transfers and who answers status questions.</p><p>Avoid inferring a particular port, vessel, sailing or direct connection from an island-specific webpage. Those arrangements belong in the provider’s service plan. Review our <a href="/hawaii-moving-shipping-process/">shipping-process guide</a> for questions about each stage.</p>'''),
 ('Plan the mainland end just as carefully','''<p>Provide a destination city or ZIP even if the final street address is pending. Tell the provider about stairs, elevator bookings, limited parking or a home that will not be ready immediately. Ask how far ahead delivery coordination happens and how changes will be communicated.</p><p>If you need temporary storage, clarify how it connects to final delivery and whether you can access your goods. Keep essential belongings with you so your personal travel and work arrangements do not depend on a single estimated delivery date.</p>'''),
 ('Bring a consistent scope to your quote request',f'''<p>A {island}-to-mainland request should include shipment size, inventory concerns, approximate timing, packing help and a vehicle if applicable. The form allows custom locations so you can describe your move accurately.</p><p>Use the <a href="/hawaii-mainland-moving-cost/">cost guide</a> to compare included services and the <a href="/hawaii-to-mainland-moving/">Hawaii-to-mainland guide</a> to review your preparation. ModelMoving can review your request for matching; a provider must confirm coverage, availability and terms.</p>''')],[(f'Does submitting a {island} request confirm pickup availability?','No. Availability and address-level coverage are confirmed by a selected provider after it reviews your move.'),(f'What should I include for a {island} pickup?',f'Include your town or ZIP, property access, inventory, approximate date and packing or storage needs, along with your mainland destination.')])
add('hawaii-moving-shipping-process','The Hawaii–Mainland Shipping Process, Step by Step','Understand household pickup, consolidation, ocean transportation, mainland handling and final delivery—and who to ask about each stage.',[
('One move, several coordinated stages','''<p>A household move across the Pacific can combine local collection, preparation for ocean transport, the ocean crossing and destination delivery. Depending on the provider, route, shipment and service plan, there may also be consolidation, storage or additional handoffs.</p><p>This is a planning framework, not a promise that every move follows the same route. Ask your provider to map the actual stages for your shipment and identify one point of contact for questions.</p>'''),
('1. Inventory, preparation and pickup','''<p>Confirm the inventory and packing scope before collection. Ask how items and condition are recorded, which documents you receive and what you should retain. Explain access constraints at the house, apartment or storage location.</p><p>At pickup, follow the provider’s documentation process and retain copies. If your shipment differs from the planned inventory, raise the change before work proceeds so the scope and any pricing consequences are clear.</p>'''),
('2. Port-area handling and consolidation','''<p>Ask whether your goods move directly into the planned ocean service or require handling, consolidation or storage first. Find out what the provider means by “ready to ship” and how it communicates changes.</p><p>Do not assume that pickup day is sailing day. Different service plans can have different preparation and handoff stages. If timing is important, ask for the expected sequence and what remains uncertain.</p>'''),
('3. Ocean transportation','''<p>Discuss the ocean stage as part of the full service plan. Ask what information you can expect about departure and arrival, and how schedule changes affect the next stages. Keep your personal travel plans and essential belongings independent of a single sailing estimate.</p><p>For background on one ocean provider’s household-goods offering, see <a href="https://www.matson.com/hhg-personal/index.html" target="_blank" rel="noopener">Matson’s household-goods information</a>. This is an independent resource, not a statement of partnership or a guarantee about the provider selected for your request.</p>'''),
('4. Arrival handling and final delivery','''<p>Ocean arrival is not necessarily final delivery. Ask how the goods are released into the next stage, who arranges onward transportation and how you will be contacted. Confirm the actual destination address and access restrictions before delivery is scheduled.</p><p>If your home is unavailable, ask about storage before the shipment reaches that decision point. On delivery, follow the provider’s inventory and condition-review process, record concerns and request its claims instructions where needed.</p>'''),
('Keep a handoff record','''<p>Save your agreed scope, inventory, receipts, contacts and written timing updates in one place. For each stage, know who is responsible for communication, what milestone comes next and what action is needed from you.</p><p>Review <a href="/how-it-works/">ModelMoving’s matching role</a> separately from the provider’s transportation responsibilities, and use the <a href="/hawaii-mainland-moving-cost/">cost guide</a> to check which stages are included in a proposal.</p>''')],[('Does every move use consolidation?','No. Ask the selected provider whether consolidation, storage or other handling is part of your particular service plan.'),('Does port arrival mean my household delivery is ready?','Not necessarily. Arrival handling and onward delivery coordination may remain. Ask your provider for the next confirmed milestone.')])
add('moving-a-car-from-hawaii-to-mainland','Moving a Car from Hawaii to the Mainland: Planning Guide','Prepare questions for Hawaii-mainland vehicle transport: booking scope, documents, preparation, collection and coordination with household goods.',[
('Treat the vehicle as its own planning task','''<p>If your car is coming with your household goods, tell the provider early. Vehicle transport may involve a separate booking, preparation checklist, drop-off process and release arrangement. Do not assume the household pickup includes the vehicle or that both arrive together.</p><p>Give the make, model, year, approximate dimensions and operating condition when the provider requests them. Mention modifications or unusual equipment so it can assess acceptance and handling requirements.</p>'''),
('Get the current preparation checklist','''<p>Ask your selected vehicle provider for its current checklist for your direction and service. Requirements can differ, so confirm documents, cleaning, fuel or battery instructions, keys and any restrictions on belongings inside the car directly.</p><p><a href="https://www.pashahawaii.com/resources/vehicles/ship-vehicle-shipping-checklists" target="_blank" rel="noopener">Pasha Hawaii’s vehicle checklists</a> describe preparation and destination pickup resources for its service. Use the checklist that belongs to your booked provider rather than assuming another company’s instructions apply.</p>'''),
('Clarify documents and authorized handoff','''<p>Ask which ownership, registration, lien or authorization documents are needed for your booking. If someone else will drop off or collect the car, confirm the authorization process before making travel arrangements.</p><p>Request the exact handoff location, appointment requirements and contact details. Do not rely on an unconfirmed port address or a general webpage when planning a timed vehicle drop-off.</p>'''),
('Plan around two arrival schedules','''<p>Your vehicle and household shipment may have different schedules. Decide how you will travel after drop-off and what transportation you need before collection at destination. Ask how arrival notices are sent and what happens if you cannot collect promptly.</p><p>Confirm whether the proposal covers terminal collection, onward transport to your address or another arrangement. If the car is being delivered inland, identify who coordinates that stage and how its scope is priced.</p>'''),
('Compare terms before agreeing','''<p>Have the provider explain the condition-record process, damage-reporting steps, protection terms and any exclusions. Keep your own dated photos and retain the handoff documents. These preparation steps are useful, but they do not create coverage or replace the provider’s written terms.</p><p>Select “Yes” under vehicle in the <a href="/#quote" data-event="hmm_quote_cta_click">moving request</a> and add any known details in notes. ModelMoving can include the need in matching; the selected provider confirms the actual vehicle service.</p>''')],[('Can I pack belongings inside the car?','Do not assume you can. Confirm the selected vehicle provider’s current restrictions before putting belongings in the vehicle.'),('Will my car and furniture arrive together?','Not necessarily. Ask for separate coordination details and plan transportation around the confirmed vehicle service.')])
add('how-it-works','How HawaiiMainlandMoving Works | ModelMoving','See how a Hawaii-mainland quote request is reviewed, matched to selected providers and developed into provider pricing and service terms.',[
('Start with a route and a useful outline','''<p>The quote form asks for your origin, destination, approximate move date and shipment size. It then asks about packing, a vehicle and your contact details. Use notes to explain access, storage, unusual items or uncertainty about the destination.</p><p>You can request either direction between Hawaii and the mainland. The form starts the conversation. You can review provider pricing and service details before deciding whether to book.</p>'''),
('ModelMoving reviews the request for matching','''<p>HawaiiMainlandMoving.com is operated by ModelMoving, a moving quote request and matching platform. Requests may be matched with selected moving partners based on the route, timing, availability and move details provided.</p><p>We use your move details to help identify relevant provider options. A selected provider will confirm availability and may ask follow-up questions or review your inventory to develop a proposal for your move.</p>'''),
('Discuss the scope with the provider','''<p>ModelMoving or selected moving partners may contact you about the request as described in the form’s consent notice. Use that conversation to confirm inventory, access, packing, timing, storage and any vehicle requirements.</p><p>Ask the provider to explain the collection, ocean and destination stages it is proposing. Keep the same scope when comparing options so differences in included work are visible.</p>'''),
('Review pricing and terms before booking','''<p>Final pricing, availability, service terms and transportation arrangements are supplied by the selected moving provider. Review its written proposal, payment conditions, cancellation terms and protection or claims provisions before agreeing.</p><p>Our role is to help you prepare your move details and connect with a suitable moving provider. Your selected provider supplies the service agreement and handles the transportation arrangements described in that agreement.</p>'''),
('Keep the plan current','''<p>If your inventory, address or timing changes, tell the provider handling your proposal. Confirm that revisions are reflected in the agreed scope. Keep copies of the inventory and communications throughout the move.</p><p>Read the <a href="/hawaii-moving-shipping-process/">shipping-process guide</a> for stage-by-stage questions, our <a href="/privacy/">privacy notice</a> for request-data handling and <a href="/terms/">terms</a> for website use.</p>''')],[('Does submitting book my move?','No. It sends a moving quote request. Any booking and transportation agreement must be made with a selected provider.'),('Who gives me the final price?','The selected moving provider supplies final pricing, service terms, availability and transportation arrangements.')])
add('about','About HawaiiMainlandMoving.com | Operated by ModelMoving','A Hawaii-mainland planning resource operated by ModelMoving, with clear logistics guidance and moving quote request matching.',[
('A clearer starting point for a Pacific move','''<p>Moving a home between Hawaii and the mainland involves more than choosing two cities. It means deciding what travels, preparing the pickup property, understanding ocean and handling stages, and coordinating a home at the other end.</p><p>HawaiiMainlandMoving.com brings those questions together. The goal is to help you understand your move well enough to request useful options and evaluate what a provider proposes.</p>'''),
('Who operates this site','''<p>The site is operated by ModelMoving, a moving quote request and matching platform that helps connect customers with selected moving partners based on route, timing, availability and move details.</p><p>We bring Hawaii-specific planning and moving quote requests together in one place, so you can start with a clearer picture of your move. Your selected moving provider confirms pricing, availability, transportation arrangements and service terms.</p>'''),
('What you can do here','''<ul><li>Plan a move in either direction between Hawaii and the mainland.</li><li>Read island-specific preparation guidance for Oahu, Maui and the Big Island.</li><li>Explore the stages that may connect pickup to final delivery.</li><li>Identify cost factors and vehicle-planning questions.</li><li>Submit your move details for quote-request matching.</li></ul><p>Kauai and custom Hawaii locations can be entered in the request form. A provider must confirm the actual coverage and service plan.</p>'''),
('How to use our guidance','''<p>Use these pages to organize your inventory, understand the transport stages and prepare useful questions. Your shipment, property access and preferred timing help the selected provider develop a service plan for your move.</p><p>Where an independent provider resource is linked, it is for additional context. A reference link is not a claim of partnership, endorsement or an offer of that provider’s service through this website.</p>'''),
('Take the next useful step','''<p>Start with the <a href="/hawaii-to-mainland-moving/">Hawaii-to-mainland guide</a> or the <a href="/mainland-to-hawaii-moving/">mainland-to-Hawaii guide</a>. If you already know your route, share the basics in the <a href="/#quote" data-event="hmm_quote_cta_click">three-step request</a>.</p><p>For more about what follows, read <a href="/how-it-works/">how matching works</a>. You can also explore the broader resources at <a href="https://modelmoving.com/?utm_source=hawaiimainlandmoving.com&amp;utm_medium=referral&amp;utm_campaign=about" data-event="hmm_modelmoving_click">ModelMoving</a>.</p>''')],[])
add('privacy','Privacy Notice | HawaiiMainlandMoving.com','How HawaiiMainlandMoving.com handles moving request details, source attribution, analytics and provider contact information.',[
('Operator and scope','''<p>This notice describes the HawaiiMainlandMoving.com website operated by ModelMoving. It covers information submitted through this site and the attribution and analytics used here. Updated September 5, 2026.</p>'''),
('Information submitted with a request','''<p>The quote form collects origin and destination, estimated move date, move size, name, phone number, email address and optional notes. Vehicle and packing answers are included with the move details. Avoid including payment information, identification documents or other sensitive information in notes.</p><p>Requests are sent through Web3Forms to support ModelMoving’s existing request-processing workflow. ModelMoving and selected moving partners may use the request to assess the move, discuss options and contact you as described by the form’s consent notice.</p>'''),
('Attribution and browser storage','''<p>The form includes campaign parameters, referring website information, the landing-page URL and the current-page URL to identify how visitors reached the site. Session storage retains entry attribution across pages in the current browser session where available. It does not store your form contact details.</p><p>This site uses Google Analytics 4 to measure visits and interactions, including quote steps and successful submissions. Google Analytics may use cookies and process browser, device and usage information under Google’s terms. The custom event implementation does not include your name, phone, email or notes.</p>'''),
('Sharing and outside services','''<p>Information may be processed by services supporting form delivery, analytics, hosting and ModelMoving’s request workflow, and shared with selected moving partners for the request. Those providers may have their own privacy policies and practices.</p><p>See <a href="https://web3forms.com/privacy" target="_blank" rel="noopener">Web3Forms’ privacy policy</a> and <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google’s privacy policy</a>. Following an external link takes you to another service; review its notice before sharing additional information.</p>'''),
('Your choices and questions','''<p>You can choose not to submit a request and can restrict cookies or storage through your browser settings. If you no longer want contact about a request, tell ModelMoving or the provider contacting you. To ask about access, correction, deletion or retention of submitted information, use the contact options on <a href="https://modelmoving.com/?utm_source=hawaiimainlandmoving.com&amp;utm_medium=referral&amp;utm_campaign=privacy_contact" data-event="hmm_modelmoving_click">ModelMoving’s website</a> and identify HawaiiMainlandMoving.com as the source.</p><p>No method of transmission or storage is completely secure. The website does not state a fixed deletion period; ask the operator about handling and retention of your specific request. This notice may be updated as the service changes.</p>''')],[])
add('terms','Website Terms | HawaiiMainlandMoving.com','Terms for using HawaiiMainlandMoving.com planning resources and quote requests, including ModelMoving’s role and provider responsibilities.',[
('Using this website','''<p>HawaiiMainlandMoving.com is a moving-information and quote-request resource operated by ModelMoving. These terms describe use of the website. Updated September 5, 2026.</p><p>Use the site for legitimate planning and requests you are authorized to make. Provide accurate details and do not submit another person’s contact information without authorization. Do not misuse the form, interfere with the site or submit unlawful content.</p>'''),
('Quote requests are not bookings','''<p>Submitting the form sends a request for review and possible matching with selected moving partners based on route, timing, availability and move details. It does not create a transportation contract, reserve a date or guarantee a price, provider, response time or number of quotes.</p><p>ModelMoving operates the request and matching platform. Final pricing, availability, service terms and transportation arrangements are provided by the selected moving provider.</p>'''),
('Information and estimates','''<p>The guides and interactive tools provide general planning information. Cost factors do not calculate an actual quote. Timeline reminders are preparation suggestions, not guaranteed pickup, sailing or delivery schedules.</p><p>Actual requirements depend on the provider, route, shipment and service plan. Confirm current acceptance rules, preparation instructions, access needs, schedules and service terms directly with the provider before booking or relying on an arrangement.</p>'''),
('Provider agreements and outside links','''<p>Review the selected provider’s written agreement, payment and cancellation terms, protection provisions and claims process. Your selected provider’s written agreement identifies the transportation services, ocean arrangements where applicable, and any protection for loss or damage.</p><p>Links to independent resources are provided for context. They do not establish a partnership or incorporate an outside provider’s service into your request. Third-party websites and services have their own terms and privacy practices.</p>'''),
('Privacy and changes','''<p>See the <a href="/privacy/">privacy notice</a> for information submitted with requests and the use of attribution and analytics. The consent shown with the form describes contact about your request.</p><p>Website content and these terms may change. For questions about the website, use the contact options at <a href="https://modelmoving.com/?utm_source=hawaiimainlandmoving.com&amp;utm_medium=referral&amp;utm_campaign=terms_contact" data-event="hmm_modelmoving_click">ModelMoving</a>. For questions about a booked service, contact the provider responsible for that agreement.</p>''')],[])
for slug,title,desc,sections,faqs in DATA:
 content=''.join(f'<section><h2>{h}</h2>{b}</section>' for h,b in sections)
 if faqs:content+='<section><h2>Questions before you move</h2>'+faqhtml(faqs)+'</section>'
 body=f'<main id="main"><div class="article-hero"><div class="wrap"><div class="breadcrumb"><a href="/">Home</a> / Moving resources</div><h1>{title.split(" | ")[0]}</h1><p>{desc}</p></div></div><div class="wrap article-layout"><article class="article-body">{content}</article><aside class="article-side"><h2>Your route. Your plan.</h2><p>Start with the basics, then discuss the details with a provider.</p><a class="btn dark" href="/#quote" data-event="hmm_quote_cta_click">Request options</a><a href="/hawaii-mainland-moving-cost/">Understand cost factors</a><a href="/hawaii-moving-shipping-process/">Explore the shipping process</a><a href="/how-it-works/">How matching works</a><p class="fine">Operated by ModelMoving.</p></aside></div>{cta()}</main>'
 page(slug,title,desc,body,faqs)
# Homepage is assembled from a checked-in template.
ref=(P.parent/'upload/Pasted text (2)(6).txt')
key_file=P/'tools/form-key.txt'
if ref.exists():key=re.search(r'name="access_key" value="([^"]+)"',ref.read_text()).group(1)
else:
 existing=(P/'index.html').read_text();key=re.search(r'name="access_key" value="([^"]+)"',existing).group(1)
home=(P/'tools/home.html').read_text().replace('{{ACCESS_KEY}}',key)
homefaq=[('Who will handle my move?','HawaiiMainlandMoving.com is operated by ModelMoving, a quote request and matching platform. A selected moving provider confirms availability, pricing, service terms and transportation arrangements.'),('Can I move from the mainland to Hawaii?','Yes. Choose Mainland to Hawaii in the form and enter your mainland origin and destination island or community.'),('How long will my move take?','Timing depends on the provider, route, shipment and service plan. Ask about the full sequence from pickup through ocean transport and final delivery, not only the sailing stage.'),('Can I include a car or request packing?','Yes. Add those needs in the Move Details step. The provider confirms whether they are included in its proposal or require separate arrangements.'),('Do you give instant prices?','No. The cost explorer explains factors that may influence pricing. Actual quotes come from providers after reviewing the move.')]
home=home.replace('{{FAQ}}',faqhtml(homefaq))
page('','Hawaii ↔ Mainland Moving | A Clearer Plan for Your Move','Plan your Hawaii-mainland move, explore island logistics and cost factors, and request moving options through ModelMoving.',home,homefaq)
urls=[BASE+'/']+[BASE+'/'+d[0]+'/' for d in DATA]
(P/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join('<url><loc>'+u+'</loc></url>' for u in urls)+'</urlset>\n')
(P/'robots.txt').write_text('User-agent: *\nAllow: /\n\nSitemap: '+BASE+'/sitemap.xml\n')
(P/'404.html').write_text('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Page not found | HawaiiMainlandMoving.com</title><link rel="stylesheet" href="/assets/site.css"></head><body>'+NAV+'<main id="main" class="section wrap"><p class="kicker">404 / A different direction</p><h1>Let’s get you back on course.</h1><p>This page could not be found.</p><a class="btn dark" href="/">Return to the homepage</a></main><script defer src="/assets/site.js"></script></body></html>')
print('Built',len(urls),'indexable pages')
