/* Run with NODE_PATH pointing to an installation of jsdom. No real requests. */
const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),code=fs.readFileSync(path.join(root,'assets/site.js'),'utf8');
let checks=0;function ok(v,m){assert.ok(v,m);checks++}
function setup(url='https://hawaiimainlandmoving.com/',referrer='',saved){const d=new JSDOM(html,{url,referrer:referrer||undefined,runScripts:'outside-only'}),w=d.window,events=[];w.gtag=(...v)=>events.push(v);w.HTMLElement.prototype.scrollIntoView=()=>{};if(saved)w.sessionStorage.setItem('hmm_attribution_v1',saved);w.eval(code);return {w,doc:w.document,events,d}}
function fill(doc,id,value){const e=doc.getElementById(id);e.value=value;e.dispatchEvent(new doc.defaultView.Event('input',{bubbles:true}))}
function next(doc){doc.querySelector('fieldset:not([hidden]) [data-next]').click()}
function complete(t){fill(t.doc,'moving-from','Oahu');fill(t.doc,'moving-to','Seattle, WA');next(t.doc);fill(t.doc,'move-size','2 Bedroom');next(t.doc);fill(t.doc,'full-name','Test Person');fill(t.doc,'phone','2025550123');fill(t.doc,'email','test@example.com')}
(async()=>{
for(const [ref,source,medium] of [['https://www.google.com/search?q=move','google','organic'],['https://www.bing.com/search?q=move','bing','organic'],['https://search.yahoo.com/','yahoo','organic'],['https://m.facebook.com/','facebook','social'],['https://www.instagram.com/','instagram','social'],['https://chatgpt.com/','chatgpt','referral'],['https://openai.com/','chatgpt','referral'],['https://routes.modelmoving.com/','modelmoving','referral'],['https://example.com/','example.com','referral'],['','direct','none']]){const t=setup(undefined,ref);ok(t.doc.querySelector('[name=traffic_source]').value===source,'source '+source);ok(t.doc.querySelector('[name=traffic_medium]').value===medium,'medium '+source);t.d.window.close()}
let t=setup('https://hawaiimainlandmoving.com/?utm_source=newsletter&utm_medium=email&utm_campaign=launch','https://google.com/');ok(t.doc.querySelector('[name=traffic_source]').value==='newsletter','UTM priority');let saved=t.w.sessionStorage.getItem('hmm_attribution_v1');t.d.window.close();t=setup('https://hawaiimainlandmoving.com/','https://hawaiimainlandmoving.com/about/',saved);ok(t.doc.querySelector('[name=traffic_campaign]').value==='launch','internal attribution retained');ok(t.doc.querySelector('[name=landing_page]').value.includes('utm_campaign=launch'),'original landing retained');
next(t.doc);ok(!t.doc.querySelector('[data-step="0"]').hidden,'empty route blocked');complete(t);ok(t.events.filter(e=>e[1]==='modelmoving_form_start').length===1,'one form start');ok(t.events.filter(e=>e[1]==='hmm_step_complete').length===2,'step events');t.doc.querySelector('[data-step="2"] [data-back]').click();ok(t.doc.getElementById('move-size').value==='2 Bedroom','back preserves values');next(t.doc);
let payload,calls=0;t.w.fetch=async(u,o)=>{calls++;payload=JSON.parse(o.body);return {ok:true,json:async()=>({success:true})}};t.doc.getElementById('vehicle').value='Yes';t.doc.getElementById('packing').value='No';t.doc.getElementById('quote-form').dispatchEvent(new t.w.Event('submit',{bubbles:true,cancelable:true}));t.doc.getElementById('quote-form').dispatchEvent(new t.w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));ok(calls===1,'duplicate blocked');ok(t.events.filter(e=>e[1]==='generate_lead').length===1,'confirmed lead only');for(const key of ['moving_from','moving_to','move_date','move_size','full_name','phone','email','notes','subject','source','source_site','route','route_page','service_area','lead_type','utm_source','utm_medium','utm_campaign','traffic_source','traffic_medium','traffic_campaign','landing_page','current_page_url','referrer','referring_site'])ok(key in payload,'payload '+key);ok(payload.route==='Oahu to Seattle, WA','dynamic route');ok(payload.notes.includes('Vehicle: Yes. Packing help: No.'),'extras in notes');ok(t.doc.getElementById('full-name').value==='','success reset');ok(!t.doc.querySelector('[data-step="0"]').hidden,'reset step');ok(!JSON.stringify(t.events).includes('test@example.com'),'no contact in analytics');t.d.window.close();
for(const mode of ['http','provider','network','json']){t=setup();complete(t);t.w.fetch=async()=>{if(mode==='network')throw Error();return {ok:mode!=='http',json:async()=>{if(mode==='json')throw Error();return {success:mode!=='provider'}}}};t.doc.getElementById('quote-form').dispatchEvent(new t.w.Event('submit',{bubbles:true,cancelable:true}));await new Promise(r=>setTimeout(r,0));ok(!t.events.some(e=>e[1]==='generate_lead'),'no false lead '+mode);ok(t.doc.getElementById('full-name').value==='Test Person','failure retention '+mode);ok(!t.doc.getElementById('submit').disabled,'retry enabled '+mode);t.d.window.close()}
t=setup();t.doc.getElementById('direction').value='to-hawaii';t.doc.getElementById('direction').dispatchEvent(new t.w.Event('change'));t.doc.getElementById('island').value='Maui';t.doc.getElementById('island').dispatchEvent(new t.w.Event('change'));t.doc.querySelector('[data-destination=California]').click();ok(t.doc.getElementById('moving-from').value==='California'&&t.doc.getElementById('moving-to').value==='Maui','reverse direction');t.doc.querySelector('[data-factor=Storage]').click();ok(t.doc.getElementById('cost-title').textContent==='Storage','cost explorer');t.doc.querySelector('[data-stage="3"]').click();ok(t.doc.getElementById('journey-title').textContent==='Ocean transportation','journey');fill(t.doc,'explore-destination','Denver');t.doc.getElementById('use-route').click();ok(t.doc.getElementById('moving-to').value==='Denver','route use');t.doc.getElementById('menu').click();ok(t.doc.getElementById('menu').getAttribute('aria-expanded')==='true','nav opens');t.doc.dispatchEvent(new t.w.KeyboardEvent('keydown',{key:'Escape'}));ok(t.doc.getElementById('menu').getAttribute('aria-expanded')==='false','nav escape');t.d.window.close();
const pages=[];function walk(dir){for(const e of fs.readdirSync(dir,{withFileTypes:true})){if(e.name.startsWith('.')||e.name==='tools')continue;const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(e.name==='index.html')pages.push(p)}}walk(root);ok(pages.length===13,'13 pages');let titles=new Set(),descs=new Set();for(const file of pages){const doc=new JSDOM(fs.readFileSync(file,'utf8')).window.document;ok(doc.querySelectorAll('h1').length===1,'one H1 '+file);const title=doc.title,desc=doc.querySelector('meta[name=description]').content;ok(!titles.has(title),'unique title');ok(!descs.has(desc),'unique description');titles.add(title);descs.add(desc);const route=path.relative(root,path.dirname(file)).split(path.sep).join('/');ok(doc.querySelector('link[rel=canonical]').href==='https://hawaiimainlandmoving.com/'+(route?route+'/':''),'canonical');for(const s of doc.querySelectorAll('script[type="application/ld+json"]')){let data=JSON.parse(s.textContent);ok(!JSON.stringify(data).includes('LocalBusiness'),'no carrier schema');for(const faq of data['@graph'].filter(x=>x['@type']==='FAQPage'))for(const q of faq.mainEntity)ok(doc.body.textContent.includes(q.name)&&doc.body.textContent.includes(q.acceptedAnswer.text),'visible FAQ')}
for(const e of doc.querySelectorAll('a[href],img[src],script[src],link[href]')){const href=e.getAttribute('href')||e.getAttribute('src');if(!href.startsWith('/')&&!href.startsWith('#'))continue;const u=new URL(href,'https://hawaiimainlandmoving.com/'+(route?route+'/':''));const target=path.join(root,u.pathname,u.pathname.endsWith('/')?'index.html':'');ok(fs.existsSync(target),'local target '+href);if(u.hash){const linked=new JSDOM(fs.readFileSync(target,'utf8')).window.document;ok(linked.getElementById(u.hash.slice(1)),'anchor '+href)}}ok(!/Dallas|Houston/.test(doc.body.textContent),'no reference remnants');}
console.log(`PASS: ${checks} checks; 13 pages; mocked success, failure, duplicate, attribution and navigation paths. No real leads submitted.`)
})().catch(e=>{console.error(e);process.exit(1)});
